version: "3.9"
services:
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_PASSWORD=DockerPassword
      - POSTGRES_USER=nameForDocker
      - POSTGRES_DB=monitoring_service
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./db/shortcut/data:/var/lib/postgresql/data
    restart: always
  lb:
    build:
      context: .
      dockerfile: DockerfileLB
    environment:
      - JDBC_URL=jdbc:postgresql://db:5432/monitoring_service
      - JDBC_USERNAME=nameForDocker
      - JDBC_PASSWORD=DockerPassword
      - JDBC_DRIVER=org.postgresql.Driver
    container_name: lb
    depends_on:
      - db
  monitoring_service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - JDBC_URL=jdbc:postgresql://db:5432/monitoring_service
      - JDBC_USERNAME=nameForDocker
      - JDBC_PASSWORD=DockerPassword
      - JDBC_DRIVER=org.postgresql.Driver
    container_name: monitoring_service
    depends_on:
      - db
      - lb