server:
  port: 7070

logging:
  file:
    name: monitoring_service.log


#spring:
#  datasource:
  #  changeLogFile: src/main/resources/db/changelog.xml
   # driver-class-name: org.postgresql.Driver
  #  url: jdbc:postgresql://localhost:5432/monitoring_service
  #  username: postgres
  #  password: password

 # jpa:
  #  hibernate:
   #   ddl-auto: update

